### ISSUE TITLE
BQ SQL Error - Could not cast literal to type DATE

### ISSUE THREAD

**Issue by eminty** [ohdsi-studies/Covid19VaccineAesiIncidenceCharacterization#11]
Modification of date casting required?

`DBMS:
bigquery

Error:
java.sql.SQLException: [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: Could not cast literal "1/1/2017" to type DATE at [10:45]

SQL:
insert into `som-nero-nigam-starr.eminty_explore`.aesi__target (cohort_definition_id, subject_id, cohort_start_date, cohort_end_date)
select 102 as cohort_definition_id, t1.person_id as subject_id, t1.visit_start_date as cohort_start_date, t1.visit_start_date as cohort_end_date
from
	(
	select person_id, visit_start_date
	from
	(
	select person_id, row_number() over (partition by person_id order by newid()) as rn1, visit_start_date
		  from `som-rit-phi-starr-prod.starr_omop_cdm5_deid_1pcent_lite_latest`.visit_occurrence
		  where visit_start_date >= '1/1/2017'
		  and visit_start_date < '1/1/2018'
	) t1
	where rn1 = 1

	union all

	select person_id, visit_start_date
	from
	(
	select person_id, row_number() over (partition by person_id order by newid()) as rn1, visit_start_date
		  from `som-rit-phi-starr-prod.starr_omop_cdm5_deid_1pcent_lite_latest`.visit_occurrence
		  where visit_start_date >= '1/1/2018'
		  and visit_start_date < '1/1/2019'
	) t1
	where rn1 = 1

	 union all

	select person_id, visit_start_date
	from
	(
	select person_id, row_number() over (partition by person_id order by newid()) as rn1, visit_start_date
		  from `som-rit-phi-starr-prod.starr_omop_cdm5_deid_1pcent_lite_latest`.visit_occurrence
		  where visit_start_date >= '1/1/2019'
		  and visit_start_date < '1/1/2020'
	) t1
	where rn1 = 1

	union all

	select person_id, visit_start_date
	from
	(
	select person_id, row_number() over (partition by person_id order by newid()) as rn1, visit_start_date
		  from `som-rit-phi-starr-prod.starr_omop_cdm5_deid_1pcent_lite_latest`.visit_occurrence
		  where visit_start_date >= '1/1/2020'
		  and visit_start_date < '1/1/2021'
	) t1
	where rn1 = 1
	) t1
	inner join
	`som-rit-phi-starr-prod.starr_omop_cdm5_deid_1pcent_lite_latest`.observation_period op1
	on t1.person_id = op1.person_id
	and DATE_ADD(IF(SAFE_CAST(op1.observation_period_start_date  AS DATE) IS NULL,PARSE_DATE('%Y%m%d', cast(op1.observation_period_start_date  AS STRING)),SAFE_CAST(op1.observation_period_start_date  AS DATE)), interval 365 DAY) <= t1.visit_start_date
	and op1.observation_period_end_date >= t1.visit_start_date

R version:
R version 4.0.2 (2020-06-22)

Platform:
x86_64-pc-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- datasets
- utils
- methods
- base

Other attached packages:
- BQJdbcConnectionStringR (0.1)
- cli (2.4.0)
- Covid19VaccineAesiIncidenceCharacterization (1.1.0)
- DatabaseConnector (4.0.0)
- MASS (7.3-51.6)`

**Comment by anthonysena** [comment]
That's a translation issue in the SQL - for my own reference, here is an example: https://github.com/ohdsi-studies/Covid19VaccineAesiIncidenceCharacterization/blob/master/inst/sql/sql_server/target/random%20visit%202017-2020.sql#L12. I'll need to update this to use the DATEFROMPARTS command to have the dates properly formatted.
