### ISSUE TITLE
Diagnostics execution instructions missing

### ISSUE THREAD

**Issue by keesvanbochove** [ohdsi-studies/Covid19VaccineAesiIncidenceCharacterization#14]
https://github.com/ohdsi-studies/Covid19VaccineAesiIncidenceCharacterization/blob/46d6f2734e625b4cdb6705bd3be3206ef48fe645/STUDY-EXECUTION.md#L6
This implies that the instruction also tells you how to run the CohortDiagnostics package, but it doesn't as far as I can see? Or does runStudy also invoke the cohort diagnostics at some point?

**Comment by anthonysena** [comment]
Hi @keesvanbochove - that was a copy/paste error. You are correct: this package does not run CohortDiagnostics as part of running the study. That can be done separately. I've updated the instructions accordingly. Thanks!
