### ISSUE TITLE
outcome sql file name error

### ISSUE THREAD

**Issue by ChenyuL** [ohdsi-studies/Covid19VaccineAesiIncidenceCharacterization#2]
GuillainBarreSyndrome IP primary.sql  in the outcome file name should be changed to 
GuillainBarreSyndrome IP Primary.sql

otherwise will have outcome cohort creation problem.

**Comment by anthonysena** [comment]
Thanks @ChenyuL for reporting this - I've pushed a fix that should address this issue now. Thanks!

**Comment by ChenyuL** [comment]
Hi @anthonysena , I got the incidence_analysis.csv result of this study.  
Is there any standardized visualization tool for this result?

**Comment by anthonysena** [comment]
Hi @ChenyuL - there is no shiny app with visualizations in the package at this time.
