### ISSUE TITLE
Unclear instructions

### ISSUE THREAD

**Issue by PRijnbeek** [ohdsi-studies/Covid19VaccineAesiIncidenceCharacterization#8]
in execute instructions i see this:

# When finished with reviewing the diagnostics, use the next command
# to upload the diagnostic results
uploadDiagnosticsResults(outputFolder, keyFileName, userName)

But it is not clear how to review the diagnostics? Is it even run?

**Comment by anthonysena** [comment]
Apologies - I'll remove that from the instructions. Thanks!
